spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

messages:
  go_seaside: "Going to seaside"
  stay_babysiter: "Stay with babysiter"
